const ADD_PLANT = "ADD_PLANT";
const ADD_BED = "ADD_BED";
const REMOVE_BED = "REMOVE_BED";
const SAVE = "SAVE";
const PLANT_SELECTED = "PLANT_SELECTED";
const REMOVE_PLANT = "REMOVE_PLANT";

export default {
  ADD_BED,
  REMOVE_BED,
  ADD_PLANT,
  REMOVE_PLANT,
  PLANT_SELECTED,
  SAVE
};
